/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorCountingSimpleC } from "./GovernorCountingSimpleC";
export type { GovernorSettingsC } from "./GovernorSettingsC";
export type { GovernorTimelockControlC } from "./GovernorTimelockControlC";
export type { GovernorVotesC } from "./GovernorVotesC";
export type { GovernorVotesQuorumFractionC } from "./GovernorVotesQuorumFractionC";
