/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { EIP712C } from "./EIP712C";
export type { GovernorC } from "./GovernorC";
