/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoFactory from "./DAOFactory";
export type { daoFactory };
import type * as governance from "./Governance";
export type { governance };
import type * as interfaces from "./Interfaces";
export type { interfaces };
import type * as votes from "./Votes";
export type { votes };
import type * as chainlink from "./chainlink";
export type { chainlink };
import type * as targetContract from "./targetContract";
export type { targetContract };
