/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as customizedGovernor from "./customizedGovernor";
export { GovernanceTimeLock__factory } from "./GovernanceTimeLock__factory";
export { GovernorContract__factory } from "./GovernorContract__factory";
