/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorCountingSimpleC__factory } from "./GovernorCountingSimpleC__factory";
export { GovernorSettingsC__factory } from "./GovernorSettingsC__factory";
export { GovernorTimelockControlC__factory } from "./GovernorTimelockControlC__factory";
export { GovernorVotesC__factory } from "./GovernorVotesC__factory";
export { GovernorVotesQuorumFractionC__factory } from "./GovernorVotesQuorumFractionC__factory";
