/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  EIP712C,
  EIP712CInterface,
} from "../../../../src/Governance/customizedGovernor/EIP712C";

const _abi = [
  {
    inputs: [],
    name: "AlreadyInitialized",
    type: "error",
  },
] as const;

export class EIP712C__factory {
  static readonly abi = _abi;
  static createInterface(): EIP712CInterface {
    return new utils.Interface(_abi) as EIP712CInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EIP712C {
    return new Contract(address, _abi, signerOrProvider) as EIP712C;
  }
}
