/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { EIP712C__factory } from "./EIP712C__factory";
export { GovernorC__factory } from "./GovernorC__factory";
