/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dev from "./dev";
export type { dev };
export type { Functions } from "./Functions";
export type { FunctionsClient } from "./FunctionsClient";
export type { FunctionsConsumer } from "./FunctionsConsumer";
export type { SalesDistributor } from "./SalesDistributor";
export type { SalesDistributorClient } from "./SalesDistributorClient";
