/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGovernanceTimeLock,
  IGovernanceTimeLockInterface,
} from "../../../src/Interfaces/IGovernanceTimeLock";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minDelay",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "proposers",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "executors",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGovernanceTimeLock__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernanceTimeLockInterface {
    return new utils.Interface(_abi) as IGovernanceTimeLockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGovernanceTimeLock {
    return new Contract(address, _abi, signerOrProvider) as IGovernanceTimeLock;
  }
}
