/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGoveranceNFTs,
  IGoveranceNFTsInterface,
} from "../../../src/Interfaces/IGoveranceNFTs";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_maximumSupply",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "string",
        name: "_shopDaoBaseURI",
        type: "string",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGoveranceNFTs__factory {
  static readonly abi = _abi;
  static createInterface(): IGoveranceNFTsInterface {
    return new utils.Interface(_abi) as IGoveranceNFTsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGoveranceNFTs {
    return new Contract(address, _abi, signerOrProvider) as IGoveranceNFTs;
  }
}
