/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGovernorContract,
  IGovernorContractInterface,
} from "../../../src/Interfaces/IGovernorContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_daoName",
        type: "string",
      },
      {
        internalType: "contract IVotes",
        name: "_token",
        type: "address",
      },
      {
        internalType: "contract TimelockController",
        name: "_timelock",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_votingDelay",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_votingPeriod",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_quorumPercentage",
        type: "uint256",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGovernorContract__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernorContractInterface {
    return new utils.Interface(_abi) as IGovernorContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGovernorContract {
    return new Contract(address, _abi, signerOrProvider) as IGovernorContract;
  }
}
