/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as customizedGovernor from "./customizedGovernor";
export type { customizedGovernor };
export type { GovernanceTimeLock } from "./GovernanceTimeLock";
export type { GovernorContract } from "./GovernorContract";
