/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chainlink from "./chainlink";
export type { chainlink };
export type { IGoveranceNFTs } from "./IGoveranceNFTs";
export type { IGovernanceTimeLock } from "./IGovernanceTimeLock";
export type { IGovernorContract } from "./IGovernorContract";
