/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721AVotes__factory } from "./ERC721AVotes__factory";
export { GovernanceNFTs__factory } from "./GovernanceNFTs__factory";
