/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutomationBase } from "./AutomationBase";
export type { AutomationCompatible } from "./AutomationCompatible";
